In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import sys
caffe_root = '/home/xuyf/caffe-dev/'  # this file should be run from {caffe_root}/examples (otherwise change this line)
sys.path.insert(0, caffe_root + 'python')

import caffe

In [3]:
caffe.set_mode_cpu()

In [16]:
net = caffe.Net("/home/xuyf/Depth-VO-Feat-master/dnncfile/fixedresults/fixed_model_okall.prototxt", "/home/xuyf/Depth-VO-Feat-master/dnncfile/fixedresults/fixed_model.caffemodel",
                caffe.TEST)     # use test mode (e.g., don't perform dropout)

In [145]:
net.params['conv_1_pose'][1].data

array([ 0.3869053 , -2.5108385 ,  0.5755283 , -0.4118497 , -0.18652925,
        0.15751313,  0.48055667,  0.15642266,  0.33836508,  0.07053496,
        0.34160578,  0.42698577,  0.09167955, -0.42969677, -0.80600584,
        0.7767141 , -0.54032737, -1.0574018 ,  0.4914017 ,  0.53992486,
       -0.32563034, -0.30898333, -0.6391293 ,  0.64259183,  0.457084  ,
       -2.5655131 , -1.3540388 ,  0.2831216 ,  0.57843435,  0.5514579 ,
        0.61397403,  1.2766342 ], dtype=float32)

In [23]:
net.params['conv_0_pose_fixed'][0].

In [128]:
net.params

OrderedDict([('conv_0_pose', <caffe._caffe.BlobVec at 0x7f7a1aa4d2f0>),
             ('conv_0_pose_fixed', <caffe._caffe.BlobVec at 0x7f7a1aa11520>),
             ('conv_1_pose', <caffe._caffe.BlobVec at 0x7f7a1aa114b0>),
             ('conv_1_pose_fixed', <caffe._caffe.BlobVec at 0x7f7a1aa11600>),
             ('conv_2_pose', <caffe._caffe.BlobVec at 0x7f7a1aa11670>),
             ('conv_2_pose_fixed', <caffe._caffe.BlobVec at 0x7f7a1aa116e0>),
             ('conv_3_pose', <caffe._caffe.BlobVec at 0x7f7a1aa11750>),
             ('conv_3_pose_fixed', <caffe._caffe.BlobVec at 0x7f7a1aa117c0>),
             ('conv_4_pose', <caffe._caffe.BlobVec at 0x7f7a1aa11830>),
             ('conv_4_pose_fixed', <caffe._caffe.BlobVec at 0x7f7a1aa118a0>),
             ('conv_5_pose', <caffe._caffe.BlobVec at 0x7f7a1aa11910>),
             ('conv_5_pose_fixed', <caffe._caffe.BlobVec at 0x7f7a1aa11980>),
             ('fc_0_pose', <caffe._caffe.BlobVec at 0x7f7a1aa119f0>),
             ('fc_1_pose', <ca

In [19]:
net.forward()

{'SE3': array([[[[ 0.9999944 , -0.00141872, -0.00304098,  0.00896987],
          [ 0.00140994,  0.9999948 , -0.00288751, -0.00800834],
          [ 0.00304506,  0.0028832 ,  0.9999912 ,  1.0743868 ],
          [ 0.        ,  0.        ,  0.        ,  1.        ]]]],
       dtype=float32)}

In [130]:
net.params['fc_0_pose'][0].data.shape

(512, 7680)

In [162]:
with open('../caffe-dev/conv_5_pose_bias.txt', 'r') as file:
    a = file.read()

In [163]:
raw = a.split()

In [164]:
fixed = np.zeros((256,))

In [165]:
for i in range(256):
    fixed[i] = float(raw[i])

In [166]:
np.save("conv_5_pose_bias.npy", fixed)

In [144]:
fixed

array([ 0.375  , -2.5    ,  0.5625 , -0.40625, -0.1875 ,  0.15625,
        0.46875,  0.15625,  0.34375,  0.0625 ,  0.34375,  0.4375 ,
        0.09375, -0.4375 , -0.8125 ,  0.78125, -0.53125, -1.0625 ,
        0.5    ,  0.53125, -0.3125 , -0.3125 , -0.625  ,  0.65625,
        0.46875, -2.5625 , -1.34375,  0.28125,  0.59375,  0.5625 ,
        0.625  ,  1.28125])

In [141]:
raw

['0.375',
 '-2.5',
 '0.5625',
 '-0.40625',
 '-0.1875',
 '0.15625',
 '0.46875',
 '0.15625',
 '0.34375',
 '0.0625',
 '0.34375',
 '0.4375',
 '0.09375',
 '-0.4375',
 '-0.8125',
 '0.78125',
 '-0.53125',
 '-1.0625',
 '0.5',
 '0.53125',
 '-0.3125',
 '-0.3125',
 '-0.625',
 '0.65625',
 '0.46875',
 '-2.5625',
 '-1.34375',
 '0.28125',
 '0.59375',
 '0.5625',
 '0.625',
 '1.28125']

In [122]:

for x in range(256):
    for y in range(256):
        for z in range(3):
            for n in range(3):
                fixed[x][y][z][n] = float(raw[x*256*3*3+y*3*3+z*3+n])

In [126]:
fixed[0][0]

array([[ 0.117188 , -0.195312 , -0.226562 ],
       [ 0.71875  ,  0.273438 ,  0.0234375],
       [ 0.195312 , -0.117188 , -0.65625  ]])

In [125]:
net.params['conv_5_pose'][0].data[0][0]

array([[ 0.12017733, -0.19631669, -0.22764082],
       [ 0.71543664,  0.2754301 ,  0.02333467],
       [ 0.19463843, -0.12027109, -0.6568382 ]], dtype=float32)

In [127]:
np.save("conv_5_pose.npy", fixed)