In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sys
caffe_root = '/home/xuyf/caffe-dev/'  # this file should be run from {caffe_root}/examples (otherwise change this line)
sys.path.insert(0, caffe_root + 'python')

import caffe

In [2]:
caffe.set_mode_cpu()

In [3]:
net = caffe.Net("/home/xuyf/Depth-VO-Feat-master/dnncfile/fixedresults/float_model.prototxt", "/home/xuyf/Depth-VO-Feat-master/dnncfile/fixedresults/fixed_model.caffemodel",
                caffe.TEST)     # use test mode (e.g., don't perform dropout)

In [4]:
net.params

OrderedDict([('conv_0_pose', <caffe._caffe.BlobVec at 0x7f3b34b57c90>),
             ('conv_1_pose', <caffe._caffe.BlobVec at 0x7f3b34b57d70>),
             ('conv_2_pose', <caffe._caffe.BlobVec at 0x7f3b34b57de0>),
             ('conv_3_pose', <caffe._caffe.BlobVec at 0x7f3b34b57e50>),
             ('conv_4_pose', <caffe._caffe.BlobVec at 0x7f3b34b57ec0>),
             ('conv_5_pose', <caffe._caffe.BlobVec at 0x7f3b34b57f30>),
             ('fc_0_pose', <caffe._caffe.BlobVec at 0x7f3b34b57fa0>),
             ('fc_1_pose', <caffe._caffe.BlobVec at 0x7f3b34aed050>),
             ('temporal_pose_0', <caffe._caffe.BlobVec at 0x7f3b34aed0c0>)])

In [12]:
net.params['temporal_pose_0'][0].data

array([[-3.1268310e-38,  2.6301307e-38, -2.8801221e-38, ...,
        -5.3550604e-38, -2.7499151e-38,  2.5043093e-38],
       [-3.4315115e-38, -2.3657898e-38, -4.1753560e-38, ...,
         4.5368333e-38,  2.5305766e-38, -2.6773881e-38],
       [-2.5329053e-38, -2.6883412e-38, -2.7246248e-38, ...,
        -4.4055745e-38,  2.5606476e-38,  2.7888311e-38],
       [-2.5230822e-38, -2.7124363e-38, -2.5025246e-38, ...,
        -3.2957436e-38,  2.2821948e-38, -2.4460023e-38],
       [-6.9064273e-38, -2.7624438e-38, -3.1328482e-38, ...,
        -3.1098742e-38,  2.4885645e-38, -2.3325204e-38],
       [-6.5711352e-38,  2.5765767e-38,  2.4260081e-38, ...,
         3.1384279e-38, -2.0667420e-38,  2.5081051e-38]], dtype=float32)

In [13]:
test = np.load("../npy/conv_0_pose.npy")

In [14]:
test

array([[[[-0.132812 , -0.164062 , -0.15625  , ..., -0.40625  ,
          -0.320312 , -0.351562 ],
         [-0.0390625, -0.140625 , -0.0078125, ..., -0.304688 ,
           0.03125  , -0.0859375],
         [-0.148438 , -0.289062 , -0.132812 , ..., -0.09375  ,
           0.179688 , -0.0859375],
         ...,
         [-0.195312 , -0.234375 , -0.148438 , ..., -0.109375 ,
          -0.09375  , -0.015625 ],
         [-0.203125 , -0.125    , -0.0703125, ..., -0.28125  ,
           0.0078125, -0.148438 ],
         [-0.203125 , -0.164062 , -0.210938 , ..., -0.109375 ,
          -0.09375  , -0.296875 ]],

        [[-0.0390625, -0.078125 ,  0.03125  , ..., -0.304688 ,
          -0.015625 , -0.109375 ],
         [-0.       ,  0.0234375, -0.210938 , ..., -0.1875   ,
          -0.       , -0.125    ],
         [-0.171875 , -0.179688 , -0.0703125, ..., -0.101562 ,
          -0.0625   , -0.210938 ],
         ...,
         [-0.1875   , -0.195312 , -0.0546875, ..., -0.148438 ,
          -0.078125 ,  0.

In [16]:
net.params['conv_0_pose'][0].data = test

AttributeError: can't set attribute

In [23]:
params = ['conv_0_pose', 'conv_1_pose', 'conv_2_pose', 'conv_3_pose', 'conv_4_pose', 'conv_5_pose']
fixed_params = {pr: (net.params[pr][0].data, net.params[pr][1].data) for pr in params}

In [18]:
train_params

{'conv_0_pose': (array([[[[-1.29125834e-01, -1.61225736e-01, -1.59901917e-01, ...,
            -4.05732125e-01, -3.20762902e-01, -3.51272196e-01],
           [-3.95569392e-02, -1.42567351e-01, -1.11904023e-02, ...,
            -3.01981509e-01,  3.16600092e-02, -8.70341286e-02],
           [-1.51843175e-01, -2.87340462e-01, -1.32529572e-01, ...,
            -9.62043852e-02,  1.76166281e-01, -8.21968764e-02],
           ...,
           [-1.96241558e-01, -2.36203313e-01, -1.44914344e-01, ...,
            -1.10607944e-01, -9.37249064e-02, -1.36814918e-02],
           [-1.99248359e-01, -1.25866532e-01, -6.84546530e-02, ...,
            -2.77402699e-01,  8.01040698e-03, -1.52028993e-01],
           [-2.03445509e-01, -1.60924882e-01, -2.13792056e-01, ...,
            -1.11972913e-01, -9.40766484e-02, -2.94510931e-01]],
  
          [[-4.07826900e-02, -7.80087337e-02,  3.37601379e-02, ...,
            -3.05509090e-01, -1.44315418e-02, -1.09242849e-01],
           [-1.91730994e-03,  2.17631273e

In [29]:
for pr_fixed in params:
    fixed_params[pr_fixed][0].flat = np.load('../npy/'+pr_fixed+'.npy').flat
    fixed_params[pr_fixed][1][...] = np.load('../npy/'+pr_fixed+'_bias.npy')

In [19]:
train_params['conv_0_pose'][0].flat

In [20]:
a = np.load('../npy/conv_0_pose.npy')

In [21]:
a.flat

In [22]:
train_params['conv_0_pose'][0].flat = a.flat

In [25]:
fixed_params['conv_0_pose'][1][...]

array([-11.259821 ,  -5.7205973, -10.472846 ,  -8.438862 , -10.438364 ,
        -8.347094 ,  -8.226535 ,   0.910158 ,  -7.5942583,  -8.891173 ,
        -9.803119 ,  -9.411487 ,   1.5893544,  -4.23845  ,  -1.484232 ,
        -1.5604887], dtype=float32)

In [26]:
net.params['conv_0_pose'][0].data

array([[[[-0.132812 , -0.164062 , -0.15625  , ..., -0.40625  ,
          -0.320312 , -0.351562 ],
         [-0.0390625, -0.140625 , -0.0078125, ..., -0.304688 ,
           0.03125  , -0.0859375],
         [-0.148438 , -0.289062 , -0.132812 , ..., -0.09375  ,
           0.179688 , -0.0859375],
         ...,
         [-0.195312 , -0.234375 , -0.148438 , ..., -0.109375 ,
          -0.09375  , -0.015625 ],
         [-0.203125 , -0.125    , -0.0703125, ..., -0.28125  ,
           0.0078125, -0.148438 ],
         [-0.203125 , -0.164062 , -0.210938 , ..., -0.109375 ,
          -0.09375  , -0.296875 ]],

        [[-0.0390625, -0.078125 ,  0.03125  , ..., -0.304688 ,
          -0.015625 , -0.109375 ],
         [-0.       ,  0.0234375, -0.210938 , ..., -0.1875   ,
          -0.       , -0.125    ],
         [-0.171875 , -0.179688 , -0.0703125, ..., -0.101562 ,
          -0.0625   , -0.210938 ],
         ...,
         [-0.1875   , -0.195312 , -0.0546875, ..., -0.148438 ,
          -0.078125 ,  0.

In [28]:
net.params['conv_0_pose'][2].data

IndexError: Index out of range

In [32]:
net.params['fc_0_pose'][0].data

array([[ 6.4031352e-40,  1.0417645e-39, -2.6246727e-39, ...,
         3.0011749e-39, -3.3366500e-39, -2.8290759e-39],
       [-5.4963270e-39, -4.9891676e-39,  3.0546163e-39, ...,
         1.9568012e-40,  2.2252536e-39, -5.1484729e-39],
       [ 8.3747730e-03, -4.5675691e-03, -2.7783936e-02, ...,
        -1.8356211e-01,  1.7743574e-02,  9.4033200e-03],
       ...,
       [-5.9838292e-38,  9.7224076e-04,  3.2199819e-37, ...,
         1.4996834e-02,  5.1584849e-03,  6.1176091e-02],
       [-2.6937216e-39, -2.2332199e-39, -4.0856903e-39, ...,
        -9.1523147e-40, -3.2856722e-39, -2.2539928e-39],
       [ 2.9652911e-01,  1.3246434e-05, -1.0235325e-01, ...,
        -6.1370838e-02,  1.5677428e-01,  4.2213384e-02]], dtype=float32)

In [33]:
net.save('float_model.caffemodel')

In [34]:
net = caffe.Net("/home/xuyf/Depth-VO-Feat-master/dnncfile/fixedresults/float_model.prototxt", "/home/xuyf/float_model.caffemodel",
                caffe.TEST)     # use test mode (e.g., don't perform dropout)

In [38]:
net.params['conv_0_pose'][1].data

array([-11.25 ,  -5.75 , -10.5  ,  -8.5  , -10.5  ,  -8.375,  -8.25 ,
         0.875,  -7.625,  -8.875,  -9.75 ,  -9.375,   1.625,  -4.25 ,
        -1.5  ,  -1.5  ], dtype=float32)